pipeline {
    agent any
    stages {
        stage("checkout"){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'git@git.pragma.com.co:DevOps/practica-java-devops.git']]])
            }
        }
        stage("scan"){
            environment {
                scannerHome = tool 'sonar_scanner'
            }
             steps {
                    //sh 'mvn clean install sonar:sonar'
                    withSonarQubeEnv('sonarqube') {
                        //sh "${scannerHome}/bin/sonar-scanner"
                        sh "mvn -f practica-devops/ sonar:sonar"
                        
                    }
                    timeout(time: 10, unit: 'MINUTES') {
                        //Sirve para detener la ejecucion si no es Success
                        waitForQualityGate abortPipeline: true
                    }
            }
        }
        stage("build"){
            steps{
                sh 'mvn -f practica-devops/ clean install'
            }
        }
    }
}